apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: postgres
    backstage.io/kubernetes-id: backstage-postgres
  name: postgres
  namespace: backstage-postgres
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres-headless
  template:
    metadata:
      labels:
        app: postgres
        backstage.io/kubernetes-id: backstage-postgres
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          value: backstage
        - name: POSTGRES_USER
          value: backstage
        - name: POSTGRES_PASSWORD
          value: backstage
        image: postgres:latest
        imagePullPolicy: Always
        name: postgres
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 250m
            memory: 256Mi
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - hostPath:
          path: /kind-pvcs/backstage-postgres/postgres-storage
          type: DirectoryOrCreate
        name: postgres-storage