kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind
nodes:
- role: control-plane
  extraMounts:
  - hostPath: PVCS_BASE_DIR
    containerPath: /kind-pvcs
- role: worker
  extraPortMappings:
  - containerPort: 30432
    hostPort: 5432
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30300
    hostPort: 3000
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30443
    hostPort: 4433
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  - containerPort: 30080
    hostPort: 8080
    listenAddress: "0.0.0.0" # Optional, defaults to "0.0.0.0"
    protocol: tcp # Optional, defaults to tcp
  extraMounts:
  - hostPath: PVCS_BASE_DIR
    containerPath: /kind-pvcs
- role: worker
  extraMounts:
  - hostPath: PVCS_BASE_DIR
    containerPath: /kind-pvcs
networking:
  disableDefaultCNI: true