apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-backend
  description: An example of a Backstage application.
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: backstage
    backstage.io/kubernetes-id: backstage
    argocd/app-name: backstage
    lighthouse.com/website-url: https://backstage.localhost:4433
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: guests
  lifecycle: production
  dependsOn:
    - resource:default/backstage-postgres
    - resource:default/backstage-elasticsearch
    - component:default/backstage-minio
  system: backstage