apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-localhost
spec:
  commonName: '*.localhost'
  secretName: wildcard-localhost
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io