apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: backstage-postgres
  description: |
    backstage-postgres description
  links:
    - title: Documentation
      url: https://www.postgresql.org/docs/
  annotations:
    github.com/project-slug: postgres/postgres
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-namespace: backstage-postgres
    backstage.io/kubernetes-id: backstage-postgres
    argocd/app-name: backstage-postgres
spec:
  type: database
  owner: guests
  system: backstage
  dependencyOf:
    - component:default/backstage-backend