apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage-postgres
  namespace: argocd
  labels:
    app: backstage-postgres
spec:
  project: default
  source:
    repoURL: https://github.com/pedrocrc/platform-laboratory-001.git
    targetRevision: HEAD
    path: backstage/postgres

  destination:
    server: https://kubernetes.default.svc
    namespace: backstage-postgres
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2