apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    app: cert-manager
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.16.2
    chart: cert-manager
    helm:
      values: |
        crds:
          enabled: true
        global:
          commonLabels:
            backstage.io/kubernetes-id: cert-manager
        podLabels:
          backstage.io/kubernetes-id: cert-manager
        webhook:
          podLabels:
            backstage.io/kubernetes-id: cert-manager

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2