apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eck-operator
  namespace: argocd
  labels:
    app: eck-operator
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    targetRevision: 2.15.0
    chart: eck-operator
    helm:
      values: |
        podLabels:
          backstage.io/kubernetes-id: eck-operator
        statefulsetLabels:
          backstage.io/kubernetes-id: eck-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: eck-operator
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
  revisionHistoryLimit: 2