apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-operator
  namespace: argocd
  labels:
    app: minio-operator
spec:
  project: default
  sources:
  - repoURL: https://operator.min.io
    targetRevision: 4.3.7
    chart: minio-operator
  - repoURL: https://github.com/pedrocrc/platform-laboratory-001.git
    targetRevision: HEAD
    path: minio-operator/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: minio-operator
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  revisionHistoryLimit: 2