apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-operator
  namespace: argocd
  labels:
    app: opentelemetry-operator
spec:
  project: default
  source:
    repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
    targetRevision: 0.75.0
    chart: opentelemetry-operator
    helm:
      values: |
        manager:
          collectorImage:
            repository: otel/opentelemetry-collector-k8s
          podLabels:
            backstage.io/kubernetes-id: opentelemetry-operator
        additionalLabels:
          backstage.io/kubernetes-id: opentelemetry-operator

  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry-operator
          
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  revisionHistoryLimit: 2