apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  labels:
    app: otel-collector
    backstage.io/kubernetes-id: otel-collector
spec:
  mode: daemonset
  daemonSetUpdateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 3
  image: otel/opentelemetry-collector-contrib:latest
  imagePullPolicy: Always
  configVersions: 3
  ingress:
    route: {}
  ipFamilyPolicy: SingleStack
  managementState: managed
  resources:
    requests:
      cpu: 500m
      memory: 256Mi
    limits:
      cpu: 900m
      memory: 1Gi
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: "Exists"
    effect: "NoSchedule"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 10000
        timeout: 10s

    exporters:
      debug: {}

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug]